[package]
name = "raster-input"
version = "0.0.0"
description = "Keyboard, mouse and gamepad input for the Raster engine."
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
raster-math = { path = "../raster-math" }
