[package]
name = "raster-2d"
version = "0.0.0"
description = "Tilemaps, sprites and animation for the Raster engine."
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
raster-math = { path = "../raster-math" }
