[package]
name = "raster-core"
version = "0.0.0"
description = "Actors, the world, and reflection: the heart of the Raster engine."
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
raster-math = { path = "../raster-math" }
raster-derive = { path = "../raster-derive" }
